### Row and Column Vectors (note: in NumPy vectors are represented as n-dimensional arrays)

In [6]:
import numpy as np
vector_row = np.array([[1, 2, 3, 4, 5]])
vector_column = np.array([[1], [2], [3], [4]])

print(vector_row)
print(vector_column)
print(vector_row.shape)
print(vector_column.shape)

[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]]
(1, 5)
(4, 1)


### Lenght of a vector

In [17]:
def vector_row_sum(the_vector):
    temp = 0
    for i in the_vector:
        temp += i**2
    return temp

length_of_vector_row_manual = np.sqrt(vector_row_sum(vector_row[0]))

def vector_column_sum(the_vector):
    temp = 0
    for i in the_vector:
        temp += i[0]**2
    return temp

length_of_vector_column_manual = np.sqrt(vector_column_sum(vector_column))

print(length_of_vector_row_manual)
print(length_of_vector_column_manual)

length_of_vector_row = np.linalg.norm(vector_row)
length_of_vector_column = np.linalg.norm(vector_column)

print(length_of_vector_row)
print(length_of_vector_column)

7.416198487095663
5.477225575051661
7.416198487095663
5.477225575051661


### Transpose of a Vector

In [149]:
def transpose_vector(the_vector):
    result = []
    for i in the_vector[0]:
        result.append(np.array([i]))
         
    return np.asarray(result)

transposed_vector_manual = transpose_vector(vector_row)
print(transposed_vector_manual)

transposed_vector = vector_row.T
print(transposed_vector)


[[1]
 [2]
 [3]
 [4]
 [5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


### Vector-vector Addition

In [162]:
v = w = np.array([[1],
                  [2],
                  [3]])

u = v + w
print(u)

u = np.add(u,w)
print(u)



[[2]
 [4]
 [6]]
[[3]
 [6]
 [9]]


### Vector-scalar Addition

In [156]:
v = np.array([[1],
              [2],
              [3]])

a = 100

u = v + a
print(u)

u = np.add(u,a)
print(u)

[[101]
 [102]
 [103]]
[[201]
 [202]
 [203]]


### Vector-vector Multiplication: Dot Product

In [166]:
v, w = np.array([[-2],[2]]), np.array([[-4],[4]])

u = np.dot(v.T,w)
print(u)

u = v.T @ w
print(u)


[[16]]
[[16]]


### Vector-vector Multiplication: Cross Product

In [4]:
v, w = np.array([[-2, 2, -1]]), np.array([[-4, 4, -5]])

u = np.cross(v,w)
print(u)

[[-6 -6  0]]


### Vector-scalar Multiplication

In [10]:
v = np.array([[-2, 2, -1]])
a = 100

u1 = v * a
u2 = np.multiply(a,v)

print(u)
print(u)

[[-200  200 -100]]
[[-200  200 -100]]


### Matrics

In [6]:
A = np.array([[0,2],  # 1st row
              [1,4]]) # 2nd row

print(f'a 2x2 Matrix:\n{A}')

a 2x2 Matrix:
[[0 2]
 [1 4]]


### Matrix-matrix Addition

In [18]:
A = np.array([[0,2],
              [1,4]])
B = np.array([[3,1],
              [-3,2]])

print(f'A+B:\n{A+B}')
print(f'np.add(A,B):\n{np.add(A,B)}')

A+B:
[[ 3  3]
 [-2  6]]
np.add(A,B):
[[ 3  3]
 [-2  6]]


### Matrix-scalar Addition

In [9]:
A = np.array([[0,2],
              [1,4]])
a = 100

print(f'A+a:\n{A+a}')
print(f'np.add(A,a):\n{np.add(A,a)}')

A+a:
[[100 102]
 [101 104]]
np.add(A,a):
[[100 102]
 [101 104]]


### Matrix-matrix Multiplication: Dot Product

In [3]:
A = np.array([[0,2],
              [1,4]])
B = np.array([[1,3],
              [2,1]])

print(A@B)
print(np.dot(A,B))

[[4 2]
 [9 7]]
[[4 2]
 [9 7]]


In [4]:
A = np.array([[0,2],
              [1,4]])
x = np.array([[1],
              [2]])

print(A@x)
print(np.dot(A,x))

[[4]
 [9]]
[[4]
 [9]]


#### Matrix-scalar Multiplication: dot product

In [6]:
A = np.array([[0,2],
              [1,4]])
a = 100

print(A*a)
print(np.multiply(A,a))

[[  0 200]
 [100 400]]
[[  0 200]
 [100 400]]


### Matrix Inverse

In [10]:
A = np.array([[1, 2, 1],
              [4, 4, 5],
              [6, 7, 7]])

print(np.linalg.inv(A))
print(np.linalg.inv(A) @ A)
print(np.round(np.linalg.inv(A) @ A))

[[-7. -7.  6.]
 [ 2.  1. -1.]
 [ 4.  5. -4.]]
[[ 1.00000000e+00  3.55271368e-15  3.55271368e-15]
 [ 0.00000000e+00  1.00000000e+00 -8.88178420e-16]
 [ 1.77635684e-15 -8.88178420e-16  1.00000000e+00]]
[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0. -0.  1.]]


### Matrix Transpose

In [12]:
print(A)
print(A.T)

[[1 2 1]
 [4 4 5]
 [6 7 7]]
[[1 4 6]
 [2 4 7]
 [1 5 7]]
