### Dataset Loading and and separates it into the training, validation, and testing sets
Note: Dataset source: https://huggingface.co/datasets/dair-ai/emotion

In [71]:
%pip install datasets

from datasets import load_dataset

dataset = load_dataset("dair-ai/emotion", "split")

Note: you may need to restart the kernel to use updated packages.


In [72]:
dataset

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 16000
    })
    validation: Dataset({
        features: ['text', 'label'],
        num_rows: 2000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 2000
    })
})

In [ ]:
# Split the dataset into train, validation, and test sets
train = dataset['train']
val = dataset['validation']
test = dataset['test']

In [74]:
import numpy as np
np_array = np.array(train)
np_array

array([{'text': 'i didnt feel humiliated', 'label': 0},
       {'text': 'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake', 'label': 0},
       {'text': 'im grabbing a minute to post i feel greedy wrong', 'label': 3},
       ..., {'text': 'i feel strong and good overall', 'label': 1},
       {'text': 'i feel like this was such a rude comment and im glad that t', 'label': 3},
       {'text': 'i know a lot but i feel so stupid because i can not portray it', 'label': 0}],
      shape=(16000,), dtype=object)

In [ ]:
# Get the lengths of each split
total_train = len(train) 
total_test = len(test)
total_val = len(val)


print(f'Total training data: {total_train}')
print(f'Total validation data: {total_val}')
print(f'Total test data: {total_test}')

Total training data: 16000
Total validation data: 2000
Total test data: 2000


In [ ]:
# Convert the training data to a pandas DataFrame and check unique labels
train_dataframe = train.to_pandas()
train_dataframe['label'].unique()

array([0, 3, 2, 5, 4, 1])

### Separates training data into 2 arrays: “tweets” and “labels”.

In [ ]:
# Function to extract tweets and labels from the dataset
def get_tweet(data):
    tweets = [x['text'] for x in data]
    labels = [x['label'] for x in data]
    return tweets, labels

tweets, labels = get_tweet(train)

tweets[:5], labels[:5]

(['i didnt feel humiliated',
  'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake',
  'im grabbing a minute to post i feel greedy wrong',
  'i am ever feeling nostalgic about the fireplace i will know that it is still on the property',
  'i am feeling grouchy'],
 [0, 0, 3, 2, 3])

### Initialize a tokenizer and calibrate it onto training data
This will assign each word a number by how commonly they appear in the dataset

In [ ]:
%pip install nltk
%pip install tensorflow

from tensorflow.keras.preprocessing.text import Tokenizer
import nltk
from nltk.stem import PorterStemmer, WordNetLemmatizer

nltk.download('wordnet')
nltk.download('omw-1.4')

stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

# Function to stem and lemmatize text
def stem_lem(text):
    tokens_stem = text.split()
    stemmed_tokens = [stemmer.stem(token) for token in tokens_stem]
    tokens_lem = ' '.join(stemmed_tokens).split()
    lemmatized_tokens = [lemmatizer.lemmatize(token) for token in tokens_lem]
    return ' '.join(lemmatized_tokens)

tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')

tweets = [stem_lem(tweet) for tweet in tweets]

tokenizer.fit_on_texts(tweets)

print(f"Tokenizer vocabulary size: {len(tokenizer.word_index)}")
print(tokenizer.texts_to_sequences([tweets[0]]), tweets[0])

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Han\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\Han\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


Tokenizer vocabulary size: 10457
[[2, 144, 3, 684]] i didnt feel humili


### Making all Sequences Same Shape

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

maxlen=50
# Function to convert tweets to padded sequences
def get_sequences(tokenizer, tweets):
    sequences = tokenizer.texts_to_sequences(tweets)
    padded = pad_sequences(sequences, truncating = 'post', padding='post', maxlen=maxlen)
    return padded

padded_train_seq = get_sequences(tokenizer, tweets)

padded_train_seq


array([[   2,  144,    3, ...,    0,    0,    0],
       [   2,   40,   49, ...,    0,    0,    0],
       [  18, 1418,    7, ...,    0,    0,    0],
       ...,
       [   2,    3,  359, ...,    0,    0,    0],
       [   2,    3,   13, ...,    0,    0,    0],
       [   2,   42,    7, ...,    0,    0,    0]],
      shape=(16000, 50), dtype=int32)

### Preparing Data for Model

In [ ]:
import numpy as np

# 
classes = set(labels)

class_to_index = dict((c,i) for i, c in enumerate(classes))
index_to_class = dict((v,k) for k, v in class_to_index.items())
names_to_ids = lambda labels: np.array([class_to_index.get(x) for x in labels])
train_labels = names_to_ids(labels)

print(classes)
print(class_to_index)
print(index_to_class)
print(train_labels)

{0, 1, 2, 3, 4, 5}
{0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5}
{0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5}
[0 0 3 ... 1 3 0]


In [81]:
# Get tweets corresponding to each class
def get_tweets_by_class(data):
    class_tweets = {i: [] for i in classes}
    for tweet, label in zip(data['text'], data['label']):
        class_tweets[label].append(tweet)
    
    print("Sample tweets for each emotion class:")
    for class_id in classes:
        print(f"\nClass {class_id}:")
        # Print first 3 tweets for each class
        for tweet in class_tweets[class_id][:3]:
            print(f"- {tweet}")

# Using the training dataset
get_tweets_by_class(train)

Sample tweets for each emotion class:

Class 0:
- i didnt feel humiliated
- i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake
- ive been feeling a little burdened lately wasnt sure why that was

Class 1:
- i have been with petronas for years i feel that petronas has performed well and made a huge profit
- i do feel that running is a divine experience and that i can expect to have some type of spiritual encounter
- i have immense sympathy with the general point but as a possible proto writer trying to find time to write in the corners of life and with no sign of an agent let alone a publishing contract this feels a little precious

Class 2:
- i am ever feeling nostalgic about the fireplace i will know that it is still on the property
- i feel romantic too
- i can t let go of that sad feeling that i want to be accepted here in this first home of mine

Class 3:
- im grabbing a minute to post i feel greedy wrong
- i am feeling grou

### Creating Model

In [ ]:
from tensorflow import keras

# 
model = keras.models.Sequential([
keras.layers.Embedding(10000,16),
keras.layers.Bidirectional(keras.layers.LSTM(20, return_sequences=True)),
keras.layers.Bidirectional(keras.layers.LSTM(20)),
keras.layers.Dense(6, activation='softmax')
])
model.compile(
     loss='sparse_categorical_crossentropy',
     optimizer='adamw',
     metrics=['accuracy']
)

### Training Model

In [ ]:
# Train the model with validation data
val_tweets, val_labels = get_tweet(val)

val_tweets = [stem_lem(tweet) for tweet in val_tweets]

val_seq = get_sequences(tokenizer, val_tweets)
val_labels= names_to_ids(val_labels)
h = model.fit(
     padded_train_seq, train_labels,
     validation_data=(val_seq, val_labels),
     epochs=20,
     callbacks=[keras.callbacks.EarlyStopping(monitor='val_accuracy', patience=2)]
)

Epoch 1/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 14s 19ms/step - accuracy: 0.4759 - loss: 1.3313 - val_accuracy: 0.6760 - val_loss: 0.8762
Epoch 2/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 10s 19ms/step - accuracy: 0.7467 - loss: 0.6452 - val_accuracy: 0.7645 - val_loss: 0.6566
Epoch 3/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 10s 19ms/step - accuracy: 0.8551 - loss: 0.4346 - val_accuracy: 0.8145 - val_loss: 0.5543
Epoch 4/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 9s 17ms/step - accuracy: 0.9051 - loss: 0.2952 - val_accuracy: 0.8400 - val_loss: 0.4841
Epoch 5/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 9s 17ms/step - accuracy: 0.9299 - loss: 0.2138 - val_accuracy: 0.8200 - val_loss: 0.5696
Epoch 6/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 9s 18ms/step - accuracy: 0.9435 - loss: 0.1746 - val_accuracy: 0.8620 - val_loss: 0.4533
Epoch 7/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 9s 17ms/step - accuracy: 0.9552 - loss: 0.1377 - val_accuracy: 0.8690 - val_loss: 0.4128
Epoch 8/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 9s 18ms/step - accuracy: 0.9622 - loss: 0.1213 - val_a

### Evaluating and Testing Model

In [ ]:
# Evaluate on the test set
test_tweets, test_labels=get_tweet(test)

test_tweets = [stem_lem(tweet) for tweet in test_tweets]

test_seq = get_sequences(tokenizer, test_tweets)
test_labels=names_to_ids(test_labels)
model.evaluate(test_seq, test_labels)

63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.8625 - loss: 0.5387


[0.5386989712715149, 0.862500011920929]

In [ ]:
import random

# Predict a random tweet from the test set
i = random.randint(0,len(test_labels)-1)
print('Sentence:', test_tweets[i])
print('Emotion:', index_to_class[test_labels[i]])
p = model.predict(np.expand_dims(test_seq[i], axis=0))[0]
print(test_seq[i])
pred_class=index_to_class[np.argmax(p).astype('uint8')]
print('Predicted Emotion: ', pred_class)

Sentence: i feel agit a lot im straddl articulaci and incoher
Emotion: 3
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 499ms/step
[  2   3 346   7 151  18   1   1   4   1   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
Predicted Emotion:  3


In [86]:
# Preprocess the tweet using the same stemming and lemmatization
tweet = "I AM ANGRY"
processed_tweet = stem_lem(tweet.lower())

# Convert to sequence and pad
sequence = tokenizer.texts_to_sequences([processed_tweet])
padded = pad_sequences(sequence, truncating='post', padding='post', maxlen=maxlen)

# Get prediction
pred = model.predict(np.expand_dims(padded[0], axis=0))[0]
predicted_emotion = index_to_class[np.argmax(pred).astype('uint8')]

print('Tweet:', tweet)
print('Predicted Emotion:', predicted_emotion)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
Tweet: I AM ANGRY
Predicted Emotion: 3
