### Dataset Loading and and separates it into the training, validation, and testing sets
Note: Dataset source: https://huggingface.co/datasets/dair-ai/emotion

In [ ]:
%pip install datasets

from datasets import load_dataset

dataset = load_dataset("dair-ai/emotion", "split")

Note: you may need to restart the kernel to use updated packages.


In [4]:
dataset

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 16000
    })
    validation: Dataset({
        features: ['text', 'label'],
        num_rows: 2000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 2000
    })
})

In [6]:
train = dataset['train']
val = dataset['validation']
test = dataset['test']

In [50]:
import numpy as np
np_array = np.array(train)
np_array

array([{'text': 'i didnt feel humiliated', 'label': 0},
       {'text': 'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake', 'label': 0},
       {'text': 'im grabbing a minute to post i feel greedy wrong', 'label': 3},
       ..., {'text': 'i feel strong and good overall', 'label': 1},
       {'text': 'i feel like this was such a rude comment and im glad that t', 'label': 3},
       {'text': 'i know a lot but i feel so stupid because i can not portray it', 'label': 0}],
      shape=(16000,), dtype=object)

In [34]:
total_train = len(train) 
total_test = len(test)
total_val = len(val)


print(f'Total training data: {total_train}')
print(f'Total validation data: {total_val}')
print(f'Total test data: {total_test}')

Total training data: 16000
Total validation data: 2000
Total test data: 2000


In [ ]:
train_dataframe = train.to_pandas()
train_dataframe['label'].unique()

array([0, 3, 2, 5, 4, 1])

### Separates training data into 2 arrays: “tweets” and “labels”.

In [7]:
def get_tweet(data):
    tweets = [x['text'] for x in data]
    labels = [x['label'] for x in data]
    return tweets, labels

tweets, labels = get_tweet(train)

tweets[:5], labels[:5]

(['i didnt feel humiliated',
  'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake',
  'im grabbing a minute to post i feel greedy wrong',
  'i am ever feeling nostalgic about the fireplace i will know that it is still on the property',
  'i am feeling grouchy'],
 [0, 0, 3, 2, 3])

### Initialize a tokenizer and calibrate it onto training data
This will assign each word a number by how commonly they appear in the dataset

In [10]:
%pip install nltk
%pip install tensorflow

from tensorflow.keras.preprocessing.text import Tokenizer
import nltk
from nltk.stem import PorterStemmer, WordNetLemmatizer

nltk.download('wordnet')
nltk.download('omw-1.4')

stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

def stem_lem(text):
    tokens_stem = text.split()
    stemmed_tokens = [stemmer.stem(token) for token in tokens_stem]
    tokens_lem = ' '.join(stemmed_tokens).split()
    lemmatized_tokens = [lemmatizer.lemmatize(token) for token in tokens_lem]
    return ' '.join(lemmatized_tokens)

tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')

tweets = [stem_lem(tweet) for tweet in tweets]

tokenizer.fit_on_texts(tweets)

print(f"Tokenizer vocabulary size: {len(tokenizer.word_index)}")
print(tokenizer.texts_to_sequences([tweets[0]]), tweets[0])

  Using cached nltk-3.9.1-py3-none-any.whl.metadata (2.9 kB)
Using cached nltk-3.9.1-py3-none-any.whl (1.5 MB)

   ---------------------------------------- 0/3 [regex]
   ---------------------------------------- 0/3 [regex]
   ---------------------------------------- 0/3 [regex]
   ---------------------------------------- 0/3 [regex]
   ------------- -------------------------- 1/3 [click]
   ------------- -------------------------- 1/3 [click]
   ------------- -------------------------- 1/3 [click]
   ------------- -------------------------- 1/3 [click]
   ------------- -------------------------- 1/3 [click]
   ------------- -------------------------- 1/3 [click]
   ------------- -------------------------- 1/3 [click]
   ------------- -------------------------- 1/3 [click]
   ------------- -------------------------- 1/3 [click]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [n

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Han\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\Han\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


Tokenizer vocabulary size: 10457
[[2, 144, 3, 684]] i didnt feel humili


### Making all Sequences Same Shape

In [12]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

maxlen=50
def get_sequences(tokenizer, tweets):
    sequences = tokenizer.texts_to_sequences(tweets)
    padded = pad_sequences(sequences, truncating = 'post', padding='post', maxlen=maxlen)
    return padded

padded_train_seq = get_sequences(tokenizer, tweets)

padded_train_seq


array([[   2,  144,    3, ...,    0,    0,    0],
       [   2,   40,   49, ...,    0,    0,    0],
       [  18, 1418,    7, ...,    0,    0,    0],
       ...,
       [   2,    3,  359, ...,    0,    0,    0],
       [   2,    3,   13, ...,    0,    0,    0],
       [   2,   42,    7, ...,    0,    0,    0]],
      shape=(16000, 50), dtype=int32)

### Preparing Data for Model

In [13]:
import numpy as np

classes = set(labels)

class_to_index = dict((c,i) for i, c in enumerate(classes))
index_to_class = dict((v,k) for k, v in class_to_index.items())
names_to_ids = lambda labels: np.array([class_to_index.get(x) for x in labels])
train_labels = names_to_ids(labels)

print(classes)
print(class_to_index)
print(index_to_class)
print(train_labels)

{0, 1, 2, 3, 4, 5}
{0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5}
{0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5}
[0 0 3 ... 1 3 0]


In [14]:
# Get tweets corresponding to each class
def get_tweets_by_class(data):
    class_tweets = {i: [] for i in classes}
    for tweet, label in zip(data['text'], data['label']):
        class_tweets[label].append(tweet)
    
    print("Sample tweets for each emotion class:")
    for class_id in classes:
        print(f"\nClass {class_id}:")
        # Print first 3 tweets for each class
        for tweet in class_tweets[class_id][:3]:
            print(f"- {tweet}")

# Using the training dataset
get_tweets_by_class(train)

Sample tweets for each emotion class:

Class 0:
- i didnt feel humiliated
- i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake
- ive been feeling a little burdened lately wasnt sure why that was

Class 1:
- i have been with petronas for years i feel that petronas has performed well and made a huge profit
- i do feel that running is a divine experience and that i can expect to have some type of spiritual encounter
- i have immense sympathy with the general point but as a possible proto writer trying to find time to write in the corners of life and with no sign of an agent let alone a publishing contract this feels a little precious

Class 2:
- i am ever feeling nostalgic about the fireplace i will know that it is still on the property
- i feel romantic too
- i can t let go of that sad feeling that i want to be accepted here in this first home of mine

Class 3:
- im grabbing a minute to post i feel greedy wrong
- i am feeling grou

### Creating Model

In [15]:
from tensorflow import keras

model = keras.models.Sequential([
keras.layers.Embedding(10000,16),
keras.layers.Bidirectional(keras.layers.LSTM(20, return_sequences=True)),
keras.layers.Bidirectional(keras.layers.LSTM(20)),
keras.layers.Dense(6, activation='softmax')
])
model.compile(
     loss='sparse_categorical_crossentropy',
     optimizer='adamw',
     metrics=['accuracy']
)

### Training Model

In [16]:
val_tweets, val_labels = get_tweet(val)

val_tweets = [stem_lem(tweet) for tweet in val_tweets]

val_seq = get_sequences(tokenizer, val_tweets)
val_labels= names_to_ids(val_labels)
h = model.fit(
     padded_train_seq, train_labels,
     validation_data=(val_seq, val_labels),
     epochs=20,
     callbacks=[keras.callbacks.EarlyStopping(monitor='val_accuracy', patience=2)]
)

Epoch 1/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 17s 22ms/step - accuracy: 0.4717 - loss: 1.3513 - val_accuracy: 0.6710 - val_loss: 0.8933
Epoch 2/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 11s 21ms/step - accuracy: 0.7561 - loss: 0.6641 - val_accuracy: 0.7850 - val_loss: 0.6236
Epoch 3/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 11s 21ms/step - accuracy: 0.8696 - loss: 0.3823 - val_accuracy: 0.8395 - val_loss: 0.4933
Epoch 4/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 11s 21ms/step - accuracy: 0.9238 - loss: 0.2434 - val_accuracy: 0.8535 - val_loss: 0.4576
Epoch 5/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 11s 22ms/step - accuracy: 0.9450 - loss: 0.1756 - val_accuracy: 0.8675 - val_loss: 0.4174
Epoch 6/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 11s 21ms/step - accuracy: 0.9557 - loss: 0.1378 - val_accuracy: 0.8635 - val_loss: 0.4562
Epoch 7/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 11s 21ms/step - accuracy: 0.9639 - loss: 0.1109 - val_accuracy: 0.8740 - val_loss: 0.4385
Epoch 8/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 11s 21ms/step - accuracy: 0.9709 - loss: 0.0961 - 

### Evaluating and Testing Model

In [ ]:
test_tweets, test_labels=get_tweet(test)

test_tweets = [stem_lem(tweet) for tweet in test_tweets]

test_seq = get_sequences(tokenizer, test_tweets)
test_labels=names_to_ids(test_labels)
model.evaluate(test_seq, test_labels)

63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8635 - loss: 0.4808


[0.48080623149871826, 0.8634999990463257]

In [18]:
import random

i = random.randint(0,len(test_labels)-1)
print('Sentence:', test_tweets[i])
print('Emotion:', index_to_class[test_labels[i]])
p = model.predict(np.expand_dims(test_seq[i], axis=0))[0]
print(test_seq[i])
pred_class=index_to_class[np.argmax(p).astype('uint8')]
print('Predicted Emotion: ', pred_class)

Sentence: i actual feel halfway benevol
Emotion: 1
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 689ms/step
[   2  176    3 3787 2286    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0]
Predicted Emotion:  1


In [19]:
sentence = 'i am devastated'
sequence = tokenizer.texts_to_sequences([sentence])
paddedSequence = pad_sequences(sequence, truncating = 'post', padding='post', maxlen=maxlen)
p = model.predict(np.expand_dims(paddedSequence[0], axis=0))[0]
pred_class=index_to_class[np.argmax(p).astype('uint8')]
print('Sentence:', sentence)
print('Predicted Emotion: ', pred_class)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
Sentence: i am devastated
Predicted Emotion:  3
